# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[(b'Jan', b'JANUARY'), (b'Feb', b'FEBRUARY'), (b'Mar', b'March')], default=b'jan', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'images')),
            ],
        ),
    ]
