# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='month',
            field=models.CharField(choices=[(b'January', b'Jan'), (b'February', b'Feb'), (b'March', b'Mar')], default=b'jan', max_length=10),
        ),
    ]
