# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_auto_20170615_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='alt_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
